### ISSUE TITLE
fail to enable autocomplete api

### ISSUE THREAD

**Issue by gky99** [atom/autocomplete-atom-api#30]
[Enter steps to reproduce:]

0. disable and enable autocomplete plus
1. disable in settings
2. enable in settings
3. oops!

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [autocomplete-atom-api](https://github.com/atom/autocomplete-atom-api) package 0.10.1

### Stack Trace

Failed to activate the autocomplete-atom-api package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/composite-disposable.js:74:19)
    at CompositeDisposable.module.exports.CompositeDisposable.add (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/composite-disposable.js:43:17)
    at requireAutocompleteManagerAsync (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/autocomplete-plus/lib/main.js:110:29)
    at Object.requireAutocompleteManagerAsync (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/autocomplete-plus/lib/main.js:31:15)
    at Object.consumeProvider (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/autocomplete-plus/lib/main.js:107:16)
    at Object.consumeProvider_2_0 (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/autocomplete-plus/lib/main.js:86:23)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:446:77)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:256:22)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:377:25
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:644:26
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:835:35)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:621:25)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:236:20)
    at Config.module.exports.Config.removeAtKeyPath (~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:386:18)
    at Package.module.exports.Package.enable (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:84:32)
    at PackageManager.module.exports.PackageManager.enablePackage (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:188:20)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/settings-view/lib/package-card.js:361:31)
```

### Commands

```
     -4:18.8.0 autocomplete-plus:activate (input.hidden-input)
     -3:30.9.0 editor:delete-to-beginning-of-word (input.hidden-input)
  2x -3:15 core:confirm (input.hidden-input)
     -2:59.7.0 core:backspace (input.hidden-input)
     -2:59.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -2:57.7.0 core:confirm (input.hidden-input)
  7x -2:17.7.0 core:backspace (input.hidden-input)
  2x -1:46.3.0 editor:delete-to-beginning-of-word (input.hidden-input)
  2x -1:33.6.0 core:backspace (input.hidden-input)
     -1:07.6.0 editor:delete-to-beginning-of-word (input.hidden-input)
  3x -1:05.2.0 core:backspace (input.hidden-input)
     -1:00.6.0 editor:delete-to-beginning-of-word (input.hidden-input)
  4x -1:00.2.0 core:backspace (input.hidden-input)
  2x -0:56.6.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -0:55.2.0 find-and-replace:select-next (input.hidden-input)
     -0:54.9.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-modules 1.6.10 
autocomplete-paths 1.0.5 
emacs-core-keys 0.2.3 
language-markdown 0.23.0 
markdown-assistant 0.2.0 
markdown-scroll-sync 2.1.2 
markdown-writer 2.6.5 
```

**Comment by 50Wliu** [comment]
Tracking at https://github.com/atom/autocomplete-plus/issues/851; please subscribe there for updates.
