### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of null

### ISSUE THREAD

**Issue by Boquete** [atom/autocomplete-atom-api#7]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.177.0
**System**: linux 3.13.0-55-generic
**Thrown From**: [autocomplete-atom-api](https://github.com/atom/autocomplete-atom-api) package, v0.9.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of null

```
At /home/piotr/.atom/packages/autocomplete-atom-api/lib/provider.coffee:28

TypeError: Cannot read property 'getPath' of null
  at Object.module.exports.readMetadata (/home/piotr/.atom/packages/autocomplete-atom-api/lib/provider.coffee:28:36)
  at /home/piotr/.atom/packages/autocomplete-atom-api/lib/provider.coffee:23:8
  at Array.forEach (native)
  at Object.module.exports.scanProjectDirectories (/home/piotr/.atom/packages/autocomplete-atom-api/lib/provider.coffee:22:35)
  at /home/piotr/.atom/packages/autocomplete-atom-api/lib/provider.coffee:17:39
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Project.module.exports.Project.setPaths (/usr/share/atom/resources/app/src/project.js:217:27)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:38:25)
  at EventEmitter.emit (events.js:119:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-atom-api, v0.9.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by benogle** [comment]
Can you upgrade to the latest version of atom?
