### ISSUE TITLE
Uncaught TypeError: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by abe33** [atom/autocomplete-atom-api#9]
[Enter steps to reproduce below:]

1. Create a new file using <kbd>cmd-n</kbd>
2. Select `Coffeescript` in the grammar selector
3. Starts typing in that file

**Atom Version**: 1.0.3-da47467
**System**: Mac OS X 10.10.4
**Thrown From**: [autocomplete-atom-api](https://github.com/atom/autocomplete-atom-api) package, v0.9.1

### Stack Trace

Uncaught TypeError: Cannot read property 'endsWith' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-atom-api/lib/provider.js:70

TypeError: Cannot read property 'endsWith' of undefined
    at Object.module.exports.isEditingAnAtomPackageFile (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-atom-api/lib/provider.js:70:21)
    at Object.module.exports.getSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-atom-api/lib/provider.js:16:17)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:234:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:221:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -0:25 application:new-file (atom-text-editor.editor.is-focused)
  2x -0:21.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:18.2.0 grammar-selector:show (atom-text-editor.editor)
     -0:16.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:15.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "coffee-lint",
      "emmet",
      "notebook",
      "rsense",
      "font-viewer",
      "react-minimap",
      "sample-minimap-plugin",
      "term2",
      "color-picker",
      "crosshairs",
      "enhanced-package-list",
      "themed-settings",
      "project-palette-finder",
      "atom-color-highlight",
      "view-tail-large-files",
      "minimap-color-highlight",
      "to-base64",
      "linter-coffeelint",
      "minimap-linter"
    ],
    "themes": [
      "one-dark-ui",
      "spacegray-dark-syntax"
    ],
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
about, v0.6.0
bezier-curve-editor, v0.7.2
block-travel, v1.0.2
bug-report, v0.7.1
figlet, v0.4.0
file-icons, v1.5.8
highlight-selected, v0.10.1
language-generic-config, v0.2.0
language-haml, v0.21.0
language-jade, v0.5.1
language-sass, v0.39.0
linter, v1.2.4
minimap, v4.12.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.7
minimap-highlight-selected, v4.3.0
minimap-pigments, v0.1.1
minimap-selection, v4.3.0
php-twig, v4.0.0
pigments, v0.8.4
project-manager, v1.15.11
red-wavy-underline, v0.3.0
spacegray-dark-syntax, v0.2.0
tabs-to-spaces, v0.11.0
travis-ci-status, v0.16.0
tree-view-breadcrumb, v0.6.1
tree-view-open-files, v0.2.4
typewriter, v0.3.3
white-cursor, v0.6.0
zentabs, v0.8.4

# Dev
minimap, v4.11.2
```

**Comment by maxbrunsfeld** [comment]
Just saw this also in a new javascript file. /cc @benogle
